apiVersion: v1
kind: ConfigMap
metadata:
  name: timescaledb-config
  labels:
    app: timescaledb 
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: {{ .Values.DBPassword | quote }}
  PGDATA: /var/lib/postgresql/data/db
  TZ: {{ .Values.Timezone | quote }}
  TS_TUNE_MAX_CONNS: "1000"
