apiVersion: v1
kind: Service
metadata:
  name: colonies-service 
  labels:
    app: colonies
spec:
  selector:
    app: colonies
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: profiler-http
      protocol: TCP
      port: {{ (int .Values.ColoniesServerProfilerPort) }}
      targetPort: {{ (int .Values.ColoniesServerProfilerPort) }}
