apiVersion: apps/v1
kind: Deployment
metadata:
  name: colonies-monitor-deployment
  labels:
    app: colonies-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colonies-monitor
  template:
     metadata:
       annotations:
         timestamp: {{ now | quote }}
       labels:
         app: colonies-monitor
     spec:
       imagePullSecrets:
       - name: {{ .Values.ImagePullSecret | quote }}
       containers:
       - name: colonies-monitor
         image: {{ .Values.ColoniesServerImage | quote }}
         imagePullPolicy: "Always"
         command: ["colonies", "monitor", "start"]
         ports:
           - containerPort: 80
         envFrom:
           - configMapRef:
               name: colonies-monitor-config
         {{ if .Values.ColoniesMonitorResourceLimit }}
         resources:
            limits:
              memory: {{ (.Values.ColoniesMonitorServerMemory | quote) }}
            requests:
              cpu: {{ (.Values.ColoniesMonitorServerCPU | quote) }}
              memory: {{ (.Values.ColoniesMonitorServerMemory | quote) }}
         {{ end }}
