apiVersion: v1
kind: Service
metadata:
  name: colonies-service 
  labels:
    app: colonies
spec:
  selector:
    app: colonies
  {{ if .Values.ExposeNodePort }}
  type: NodePort
  {{ end }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      {{ if .Values.ExposeNodePort }}
      nodePort: {{int .Values.NodePort }}
      {{ end }}
    - name: profiler-http
      protocol: TCP
      port: {{ (int .Values.ColoniesServerProfilerPort) }}
      targetPort: {{ (int .Values.ColoniesServerProfilerPort) }}
