{{ if .Values.Ingress }}
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: johank-colonies-ingress
  namespace: johank-colonies
spec:
  rules:
  - host: {{ .Values.ColoniesServerHostname | quote }} 
    http:
      paths:
        - pathType: Prefix 
          path: /
          backend:
            service:
              name: colonies-service
              port: 
                number: 80
  tls:
    - hosts:
        - {{ .Values.ColoniesServerHostname | quote }}
      secretName: johank-colonies-tls-secret
{{ end }}
