apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: colonies-postgres-statefulset
  labels:
    app: colonies-postgres
spec:
  serviceName: "colonies-postgresql-internal"
  replicas: 1
  selector:
    matchLabels:
      app: colonies-postgres
  template:
     metadata:
       labels:
          app: colonies-postgres
     spec:
         imagePullSecrets:
         - name: {{ .Values.ImagePullSecret | quote }}
         containers:
           - name: timescaledb
             image: {{ (.Values.DBImage) }} 
             imagePullPolicy: "IfNotPresent"
             ports:
               - containerPort: 5432
             envFrom:
               - configMapRef:
                   name: colonies-postgres-config
             volumeMounts:
               - mountPath: /var/lib/postgresql/data
                 name: colonies-postgresdb
             resources:
                limits:
                  memory: {{ (.Values.DBMemory | quote) }}
                requests:
                  memory: {{ (.Values.DBMemory | quote) }}
         volumes:
           - name: colonies-postgresdb
             persistentVolumeClaim:
               claimName: colonies-postgresql-pvc
