apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  labels:
    app: registry
data:
  REGISTRY_AUTH: "htpasswd"
  REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
  REGISTRY_AUTH_HTPASSWD_PATH: "/auth/registry.password"
  REGISTRY_HTTP_ADDR: 0.0.0.0:6000
  REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "/data"
