{{ if .Values.Ingress }}
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: registry-ingress
  annotations:
    kubernetes.io/ingress.class:  {{ .Values.IngressController }} 
    nginx.ingress.kubernetes.io/proxy-body-size: 0m
    {{ if .Values.CertManager }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{ end }}
spec:
  rules:
  - host:  {{ .Values.Hostname | quote }} 
    http:
      paths:
        - pathType: {{ .Values.IngressPathType }}
          path: /
          backend:
            service:
              name: registry-service
              port: 
                number: 6000
  tls:
    - hosts:
        - {{ .Values.Hostname | quote }}
      secretName: reg-tls
{{ end }}
