apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ (.Values.StorageClassName) }}
  resources:
    requests:
      storage: {{ (.Values.Disk) }}
