apiVersion: v1
kind: Service
metadata:
  name: registry-service
  labels:
    app: registry
spec:
  selector:
    app: registry
  {{ if .Values.ExposeNodePort }}
  type: NodePort
  {{ end }}
  ports:
    - name: http
      protocol: TCP
      port: 6000
      targetPort: 6000
      {{ if .Values.ExposeNodePort }}
      nodePort: {{int .Values.NodePort }}
      {{ end }}
