apiVersion: v1
kind: Service
metadata:
  name: colonies-prometheus-service 
  labels:
    app: colonies-prometheus
spec:
  selector:
    app: colonies-prometheus
  ports:
    - name: http
      protocol: TCP
      port: 9090 
      targetPort: 9090
