IngressController: "traefik"

NotebookHostname: "notebook.colonyos.io"
NotebookJupyterToken: "JvLQAMPm8HVHizwrqNMK"
NotebookImage: "colonyos/notebook:v1.0.12"
  #NotebookStorageClass: local-path
NotebookStorageClass: longhorn
NotebookStorageSize: "100Gi"
NotebookResourceLimit: false
NotebookServerCPU: "1000m"
NotebookMemory: "8Gi"
NotebookGPU: false
NotebookGPUs: 1
NotebookGPUType: "nvidia-gtx-2080ti"

ColoniesServerHost: "colonies.colonyos.io"
ColoniesServerPort: 443
ColoniesServerTLS: "true" 
ColoniesColonyId: "79f4131d1666617db31ec3ac313f0ebb5a7e6aba06123ed59edb5f5af02a1494"
ColoniesColonyPrvKey: "d82548d819621c944383ee5f31a552ecada386a5c1052493e9858ba8091408a4"
ColoniesExecutorId: "63ff4a50c1233f70e1134db6a62adf339e9012b775dd9831b2d9ef0ec152efe3"
ColoniesExecutorPrvKey: "1c92b99849382e4e7db354fd6d10da44dbce759b72f9bd83d363b16e3d9e981e"

AWSS3Endpoint: "s3.colonyos.io:443"
AWSS3TLS: "true"
AWSS3InsecureSkipVerify: "false"
AWSS3Accesskey: "erCHroCm0qvZuWqtzi6N"
AWSS3Secretkey: "IAFfzp8bg6OocRiR8nRccujmJd1VMlRnh12txx8U"
AWSS3Region: ""
AWSS3Bucket: "colonies-prod"
