apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ (.Values.StorageClassName) }}
  resources:
    requests:
      storage: {{ (.Values.BackupStorage) }} 
