apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-config
  labels:
    app: ml 
data:
  COLONIES_SERVER_HOST: {{ .Values.ColoniesServerHost | quote }}
  COLONIES_SERVER_TLS: {{ .Values.ColoniesServerTLS | quote }}
  COLONIES_SERVER_PORT: {{ .Values.ColoniesServerPort | quote }} 
  COLONIES_COLONY_ID: {{ .Values.ColoniesColonyId | quote }}
  COLONIES_COLONY_PRVKEY: {{ .Values.ColoniesColonyPrvKey | quote }}
  COLONIES_EXECUTOR_ID: {{ .Values.ColoniesExecutorId | quote }}
  COLONIES_EXECUTOR_PRVKEY: {{ .Values.ColoniesExecutorPrvKey | quote }}
  AWS_S3_ENDPOINT: {{ .Values.AWSS3Endpoint | quote }}
  AWS_S3_ACCESSKEY: {{ .Values.AWSS3Accesskey | quote }}
  AWS_S3_SECRETKEY: {{ .Values.AWSS3Secretkey | quote }}
  AWS_S3_REGION_KEY: {{ .Values.AWSS3Region | quote }}
  AWS_S3_BUCKET: {{ .Values.AWSS3Bucket | quote }}
  AWS_S3_TLS: {{ .Values.AWSS3TLS | quote }}
  AWS_S3_SKIPVERIFY: {{ .Values.AWSS3InsecureSkipVerify | quote }}
  EXECUTOR_TYPE: {{ .Values.ExecutorType | quote }} 
  EXECUTOR_SW_NAME: {{ .Values.ExecutorImage | quote }} 
  EXECUTOR_SW_TYPE: "Kubernetes"
  EXECUTOR_SW_VERSION: "n/a"
  EXECUTOR_HW_CPU: {{ (.Values.ExecutorCPU | quote) }}  
  EXECUTOR_HW_MODEL: "Pod"
  EXECUTOR_HW_MEM: {{ (.Values.ExecutorMemory | quote) }}
  EXECUTOR_HW_STORAGE: "n/a"
  EXECUTOR_HW_GPU_COUNT: {{ .Values.ExecutorGPUs | quote }}
  EXECUTOR_HW_GPU_NAME: {{ .Values.ExecutorGPUType | quote }}
  EXECUTOR_LOCATION_DESC: {{ .Values.ExecutorLocationDesc | quote }} 
  EXECUTOR_LOCATION_LONG: {{ .Values.ExecutorLocationLong | quote }}
  EXECUTOR_LOCATION_LAT: {{ .Values.ExecutorLocationLat | quote }}
