apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-deployment
  labels:
    app: ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml
  template:
     metadata:
       labels:
          app: ml 
     spec:
         {{ if .Values.ExecutorGPU }}
         nodeSelector:
            accelerator: {{ .Values.ExecutorGPUType }}
         {{ end }}
         containers:
           - name: ml 
             image: {{ .Values.ExecutorImage | quote }} 
             imagePullPolicy: "Always"
             envFrom:
               - configMapRef:
                   name: ml-config
             resources:
               limits:
                 {{ if .Values.ExecutorResourceLimit }}
                 memory: {{ (.Values.ExecutorMemory | quote) }}
                 {{ end }}
                 {{ if .Values.ExecutorGPU }}
                 nvidia.com/gpu: {{ .Values.ExecutorGPUs | quote }}
                 {{ end }}
               requests:
                 {{ if .Values.ExecutorResourceLimit }}
                 cpu: {{ (.Values.ExecutorCPU | quote) }}
                 memory: {{ (.Values.ExecutorMemory | quote) }}
                 {{ end }}
                 {{ if .Values.ExecutorGPU }}
                 nvidia.com/gpu: {{ .Values.ExecutorGPUs | quote }}
                 {{ end }}
