Ingress: false 
ExposeNodePort: true
NodePortAPI: 31000  # must be in range 30000-32767
NodePortConsole: 31001  # must be in range 30000-32767
ConsoleHostname: "minio.colonyos.io"
APIHostname: "s3.colonyos.io"
Username: "admin"
Password: "admin12345"
Image: "minio/minio:latest"
Timezone: "Europe/Stockholm"
StorageClassName: longhorn
StorageSize: "10Gi"

