apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeexecutor-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.StorageClass }}
  resources:
    requests:
      storage: 1Gi
