apiVersion: v1
kind: Service
metadata:
  name: minio-service-api
  labels:
    app: minio
spec:
  selector:
    app: minio
  {{ if .Values.ExposeNodePort }}
  type: NodePort
  {{ end }}
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
      {{ if .Values.ExposeNodePort }}
      nodePort: {{int .Values.NodePortAPI }}
      {{ end }}
