apiVersion: v1
kind: Service
metadata:
  name: minio-service-console
  labels:
    app: minio
spec:
  selector:
    app: minio
  {{ if .Values.ExposeNodePort }}
  type: NodePort
  {{ end }}
  ports:
    - name: http
      protocol: TCP
      port: 9001
      targetPort: 9001
      {{ if .Values.ExposeNodePort }}
      nodePort: {{int .Values.NodePortConsole }}
      {{ end }}
