apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: colonies-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
spec:
  rules:
  - host: {{ .Values.ColoniesServerHostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: colonies-service
          servicePort: 80 
