apiVersion: apps/v1
kind: Deployment
metadata:
  name: coloniesmonitor-deployment
  labels:
    app: coloniesmonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coloniesmonitor
  template:
     metadata:
       annotations:
         timestamp: {{ now | quote }}
       labels:
         app: coloniesmonitor
     spec:
       containers:
       - name: coloniesmonitor
         image: {{ .Values.ColoniesServerImage | quote }}
         imagePullPolicy: "Always"
         command: ["colonies", "monitor", "start"]
         ports:
           - containerPort: 80
         envFrom:
           - configMapRef:
               name: coloniesmonitor-config
