apiVersion: v1
kind: Service
metadata:
  name: coloniesmonitor-service 
  labels:
    app: coloniesmonitor
spec:
  selector:
    app: coloniesmonitor
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
