apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: colonies-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: colonies-redirect@kubernetescrd
spec:
  rules:
  - host: {{ .Values.ColoniesServerHostname | quote }} 
    http:
      paths:
        - pathType: Prefix 
          path: /
          backend:
            service:
              name: colonies-service
              port: 
                number: 80
  tls:
    - secretName: colonies-tls
      hosts:
        - {{ .Values.ColoniesServerHostname | quote }}
