apiVersion: v1
kind: ConfigMap
metadata:
  name: coloniesmonitor-config
  labels:
    app: coloniesmonitor
data:
  COLONIES_MONITORPORT: "80"
  COLONIES_MONITORINTERVALL:  {{ .Values.ColoniesMonitorIntervall | quote }}
  COLONIES_SERVERHOST: {{ .Values.ColoniesServerInternalHostname | quote }} 
  COLONIES_SERVERPORT: "80" 
  COLONIES_SERVERID: {{ .Values.ColoniesServerID | quote }} 
  COLONIES_SERVERPRVKEY: {{ .Values.ColoniesServerPrvKey| quote }}
  COLONIES_TLS: "false"
