apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    app: prometheus 
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      external_labels:
        monitor: 'codelab-monitor'

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: {{ .Values.ScrapeIntervall}} 
        static_configs:
          - targets: ['{{ .Values.ColoniesMonitoringServer }}']
