apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus 
  template:
     metadata:
       annotations:
         timestamp: {{ now | quote }}
       labels:
         app: prometheus
     spec:
       containers:
       - name: prometheus
         args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
         image: {{ .Values.PrometheusImage | quote }}
         imagePullPolicy: "Always"
         ports:
           - containerPort: 9090
         volumeMounts:
          - name: prometheus-config-volume
            mountPath: /etc/prometheus/
          - name: prometheus-storage-volume
            mountPath: /prometheus/
       volumes:
         - name: prometheus-config-volume
           configMap:
             defaultMode: 420
             name: prometheus-server-conf
         - name: prometheus-storage-volume
           persistentVolumeClaim:
             claimName: prometheus-storage-pvc
