kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeexecutor-role-binding
  namespace: {{ .Values.ExecutorK8sNamespace }}
subjects:
- kind: ServiceAccount
  name: kubeexecutor-account
  namespace: {{ .Values.ExecutorK8sNamespace }}
  apiGroup: ""
roleRef:
  kind: Role
  name: kubeexecutor-role
  apiGroup: ""
