# General settings
#StorageClassName: longhorn 
StorageClassName: local-path 
Timezone: "Europe/Stockholm"

Ingress: true 
ExposeNodePort: false
NodePort: 30000  # must be in range 30000-32767 
# IngressController: nginx
IngressController: traefik 
ColoniesServerHostname: "colonies.colonyos.io"

  # Colonies server settings
ColoniesDBHost: "colonies-postgres-service.colonyos"
ColoniesDBPort: "5432"
ColoniesServerReplicas: 1 
ColoniesServerImage: "colonyos/colonies:v1.5.1"
ColoniesServerID: "039231c7644e04b6895471dd5335cf332681c54e27f81fac54f9067b3f2c0103"
ColoniesServerPrvKey: "fcc79953d8a751bf41db661592dc34d30004b1a651ffa0725b03ac227641499d"
ColoniesResourceLimit: false 
ColoniesServerCPU: "4000m" 
ColoniesServerMemory: "16000Mi" 
ColoniesServerProfiler: false
ColoniesServerProfilerPort: 6060 
ColoniesCronCheckerPeriod: "1000"
ColoniesGeneratorCheckerPeriod: "500"
ColoniesVerbose: true
ColoniesExclusiveAssign: true
ColoniesAllowExecutorReregister: false
ColoniesRetention: false 
ColoniesRetentionPolicy: 604800 # 60 seconds * 60 * 24 * 7 = 604800 (1 week)

# PostgreSQL settings
DBUser: "postgres"
DBPassword: "rFcLGNkgsNtksg6Pgtn9CumL4xXBQ7"
DBImage: timescale/timescaledb:2.10.0-pg12
DBResourceLimit: false
DBCPU: "1000m"
DBMemory: "1000Mi"
DBStorage: 10Gi
TimescaleDB: true

# Colonies monitoring server settings
ColoniesMonitorInterval: 10
ColoniesServerInternalHostname: "colonies-service.colonyos"
ColoniesMonitorResourceLimit: false
ColoniesMonitorServerCPU: "1000m"
ColoniesMonitorServerMemory: "8Gi"

# Prometheus settings 
PrometheusImage: prom/prometheus
PrometheusStorage: 10Gi
PrometheusResourceLimit: false
PrometheusCPU: "1000m"
PrometheusMemory: "8Gi"
ScrapeIntervall: 10s
ColoniesMonitoringServer: colonies-monitor-service.colonyos
