Replicas: 1
StorageClass: "longhorn"
ExecutorDockerImage: "colonyos/kubeexecutor"
ColoniesServerHost: "server.colonyos.io"
ColoniesServerPort: 443
ColoniesTLS: true
ColoniesColonyID: ""
ColoniesColonyPrvKey: ""
ColoniesExecutorID: ""
ColoniesExecutorPrvKey: ""
AWSS3Endpoint: ""
AWSS3AccessKey: ""
AWSS3SecretKey: ""
AWSS3Region: ""
AWSS3Bucket: "colonies-prod"
AWSS3TLS: "true"
AWSS3SkipVerify: "false"
ExecutorResourceLimit: true
ExecutorMemory: "6000Mi"
ExecutorCPU: "2000m"
ExecutorType: "borg-kubeexecutor"
ExecutorSWName: "colonyos/kubeexecutor"
ExecutorSWType: "k8s"
ExecutorSWVersion: "22.05.08"
ExecutorHWCPU: "32000m"
ExecutorHWModel: "AMD Ryzen 9 5950X (32) @ 3.400GHz"
ExecutorHWNodes: "3"
ExecutorHWMem: "128GB"
ExecutorHWStorage: "4TB"
ExecutorHWGPUCount: "3"
ExecutorHWGPUMem: "12GB"
ExecutorHWGPUNodesCount: "1"
ExecutorHWGPUName: "nvidia_3080ti"
ExecutorLocationLong: "65.664406"
ExecutorLocationLat: "22.086844"
ExecutorLocationDesc: "Rutvik, Sweden"
ExecutorFSDir: "/cfs"
ExecutorK8sName: "kubeexecutor"
ExecutorK8sNamespace: "kubeexecutor"
ExecutorK8sPVC: "kubeexecutor-pvc"
