# General settings
StorageClassName: rook-ceph-fs
Timezone: "Europe/Stockholm"

# Colonies server settings
ColoniesServerHostname: "colonies-johank.icedc.se"
ColoniesServerReplicas: 3 
ColoniesServerImage: "colonyos/colonies:latest"
ColoniesServerID: "039231c7644e04b6895471dd5335cf332681c54e27f81fac54f9067b3f2c0103"
ColoniesServerPrvKey: "fcc79953d8a751bf41db661592dc34d30004b1a651ffa0725b03ac227641499d"
ColoniesServerCPU: "3000m"
ColoniesServerMemory: "10000Mi"

# PostgreSQL settings
DBPassword: "f3TeMqqx6Ds5zubDgd5C9tELv24xq4WKRypVq"
DBImage: timescale/timescaledb:latest-pg12
DBCPU: "3000m"
DBMemory: "10000Mi"
DBStorage: 10Gi
